apiVersion: v1
kind: Service
metadata:
  name: {{ node }}-{{ uuid }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8545
  selector:
    app.kubernetes.io/name: {{ node }}-{{ uuid }}
