apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secret
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    JWT_SECRET: AgDT9eiYHpsf0vIz+dtQPc3/udVI56oQawckCaPYLGs2UaezVfxDZXEq/zirK0uTFYpx0ST5HRzSRpTWjmg50ZJF2ppA/VXGNnwpbbIrCAz7a0qzPT7h1hwa5b3OjyDN/5ESwKyPl3fqXdSOjRpEv3BvQ8x/V59u+5R0Etq1whYfZfb3lCBSZ6qNV/R8S8dWFDLkEitk9Wx1yl0y2a0nv6Wsiyz1sh11UUecpwkqJ1VbKtbknc4bAkjZEebjupetI259/KzuG0AAuGt2hGVLKFPT0KMGL7l3sdvqsuqCO7ARb3Nz5CvPrXE9+uOd6TnmR/tQT1PsIT+I+i6i10MW15ZY+nFXbVJtnMaoYykkmOmYruDF7hWm75yWlVkVqVYLZOJIb8nsKNxfpc/1i0e8YQBBqXt+0F056JNjgjikQA7OSs5gTA10tYMt9oufK6+vZUxfkxAlVtVNwdi4qv8lnbjprUJSBeHFHPQF8HPFQyf8RzzWf+cxtuO6C8ubvvlMdr3j1GlIrjI3DYdikBYqQZ5evt7fpN0WByyH0B9JM1WpqjwGGtUts0ob6XCxZN58sYf0lt7NqeX/LQay3xdgL2WpFN2DAJokFGeu5ms8MpYMoLz9Xvq6WeK7YOmIgt2UZnYBUVclZOXlUz0UlHLDiSJM7hO5f0tn2CHVHN62SQKMINlftnVX0VbR9mzy1tojlrzwn0vUHGA=
    DATABASE_URL: AgCqvWhO+JgBMyk1xS81d8aKW8wvaC1Nsw7qpR2YXCYuM5E5+38n8AHMwrBvm30oRapWCC2t9cIFzSerTyh/nE7VVPIToe8rFWMk2YUdcHUFFhc/KDgBsll1PMDUP0VZW58pwGiEvwpaPx2uIFDIwlFBbNIORpjtfE87MM1dEA7S2ZyrYjsIRY1/+H/KLEGDaJ0azHw7dApgzKgLsk/3MwoHCxJKBp3z96npuIaImdoHwHq7000kTjhMmTtBc6kMol9Z3RkKNnTmuSVq39Q5XHGRM1pbs0zpGhutfq5BGbnpXd3R1SQbNol8nmA778s0SP7LBjNRhECyM7ZdBWGxbMBtZ10F5kI1eXxTHY4Dyg9caxNiuBJsTfbwChnJFDcuGJhljB/hLzXIusxEmTGm5aW9MAgM+5eNL8Vp/82pquF0u3qMkz9j1OcEBEVQLBe3E0OEBgAwUBM4DQq/TYbQY1ShzAfyPqj60KaKs8NpN/FOFqm7pDj0qN2s0NQu/RwtHuTAuhNl96QcPESzTavYLy+W+r8deD27EI7/7p7/OlMAHAFTvGC9ZcEenE/+c/s5GUX4Q3bAsNA1kD72NAau/fdaJo+brUNeojVjnQmqDs+QmlSxPQuz9rBv2cSRt7INaHLDiCILbJTzmypTrXiRA+ciqpKwGXVKB7Q3bPBq5JIdw5ElJVX7RI71P/KTWRnTHHqHygITS+BP60EZtLyTBjdSMnGx4Bcej7a9XtnjgCAj5uQ7DI+YB3aMna8sTeBd7ItOWmPY6r1aGTqdC7Si6TazkMCN1Sx1ECbp43gc94yp/Ls=
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: default
    type: Opaque
