apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ADDRESS: 0.0.0.0:3000

  DATABASE_MAX_CONNECTIONS: "20"

  KUBECONFIG: /root/.kube/config
  TEMPLATES: templates/*
  DEPLOYMENT_FILE: deployment.yaml
  SERVICE_FILE: service.yaml
