apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    POSTGRES_USER: AgCDrjtlF18t8hEPUEwT/RiFHAomhViGXtN5OHp9Ywna0Gc07OhuZ2qUURfILXux7Rji1X16SNw/vxOVK7en4HENBCiiPV+mU+msN9O8hT/uapkX1xKshy42d20zixgHLYjBX2oibKKPw80W1ofkufPGkR/v2GimacmNl5iFOLuPOz+PZsGhz2sri/ilh4ID1UzvKAtNktUS2JFUHwA45mIzJ26NxLFDxVv1ZsUyUdpjMIfeEyPInY0mFAGzVz1n5BvgmtWd4sIBlNtK5hRqJiP0RwWnBC2rrDp1UCNYNcufBgE96WQj9hklWVO7P9ybKemmSnjV7lqQzXpX4iYCTdBP6x2Au9oSsYwKSia2V1Ftr7gf9LHWyzKi8YruBvgvJ5oO7Qwmbh0E/HfkKoMCy6+qK1IhJRSr4CiXVGBAb6JGZzG3EhhBjTP8dS5xKENyGJryX5whPOfk+IyzH0ge+ujZMpO3+hoUA/VC6BtpCbjgxIOPVa4eI2mepEMf6zPIlrtHruP30z+1mPPnJ187kk6rrdTqHkoGRkFw5uJbt3shGbVFBfi/8enCoYQ1j4BlUf7NTYGybhdSzqS+NA1cCFR6H16nJxodBrPWX0Oa4HT2a3U6gyHnixKAdJ8wYcszLrYzxdEDLD3mBXopmBBgjsdD8lAlzi47Lxt/qqAKt5tnA6482G4Y/rNGqjIHrHdXyuIVgOzBfAbPZg==
    POSTGRES_PASSWORD: AgClX3Eba/jis+R4grR6K/NMbZKeUv8cHKRP08BX2cS5AYlBr8sWQhe/6wLlv6B9jhiHYkZT3nZjXE/OaFkhtPhS0lUlfE+RNRuZOwwY1J18A4RwYVArAEGkZ5QhXzJL9AHZCOFw3H8CIOVeEUajRoggg8TJ/Ku+yD8/pB0EReLM1Fa4wF/aa9PWi8xcv+ho8n8sZpwlOOe+weG/FObppjyMebgJe4RdL1vFCKvI720tN9UI7T5aYLBHCafgZOpL1z5uzr63CjBDsW6DUc+QtwVkDFnpSsJaBgqH1TaOopiZRCP9yM0fidw6X0amFLSmfjLcU2SE6rJnrs2Q4+FDNIFkLNduTYeSS6Ku6wyspMAkpO9dHjLYUAvW+OrR1wqkgDI64tibqM0mBf299ukPNv+kX1kWOEZlej3+Rys2HFzbUSJ5GUSvtjio9uCRFVMi5jaNJPz5td9wtSyrp/MF1FqStVOa6T4e2LgcbmY1Xq3f9sXcD2cUAoHpfSlRFAkb4WW6v6P4498ZQ24i5Ly1P0gXZaZ38h1J7aFkTwUFe9Z0OwznswK8iGkq+Vu0vp8aWfqwGKZDuQeKDbVrPQF/VOrtaPGxZ1UW1NPrq/7481jks9J0aGsedkVmQ/faps5ehifs5ujYfKIyeIzM09rDzeR6xMCB5JSYhdHa1sHBH8rJ/yhZpDzv2s7apM1m5KXoeUwQnSmRzy7mT374H/GzaviSC3VMjtYclO8gcpuXfRo=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
