name: Frontend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-frontend

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-frontend

      - name: Run ESLint
        working-directory: ./frontend
        run: pnpm lint

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-frontend

      - name: Check code formatting
        working-directory: ./frontend
        run: pnpm format:check
